# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_bbspost_p_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbspost',
            name='P_BestChild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='web.BBSPost'),
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='P_Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='web.BBSPost'),
        ),
    ]
