# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20161218_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbsuser',
            name='U_Honor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
