# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_bbsuser_u_honor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHasNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BBSPost')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BBSUser')),
            ],
        ),
    ]
