# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_userhasnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbspost',
            name='P_Level',
            field=models.IntegerField(default=0),
        ),
    ]
