# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_bbspost_p_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LabelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.CourseLabel')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BBSUser')),
            ],
        ),
    ]
