# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_courselabel_userfollowlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhascourse',
            name='Score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
