# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_userdislikecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbsuser',
            name='U_NewUser',
            field=models.IntegerField(default=1),
        ),
    ]
