# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-18 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_bbsuser_u_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbscourse',
            name='C_Term',
            field=models.CharField(default='2000-2001-1', max_length=15),
        ),
    ]
