# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-18 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_bbscourse_c_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbscourse',
            name='C_Term',
            field=models.CharField(max_length=15),
        ),
    ]
