# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-18 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20170218_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbscourse',
            name='C_Term',
        ),
        migrations.AddField(
            model_name='userhascourse',
            name='Term',
            field=models.CharField(default='2001-2002-1', max_length=15),
        ),
    ]
