# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_userlikecourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbspost',
            name='P_DislikeNum',
            field=models.IntegerField(default=0),
        ),
    ]
