# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_bbspost_p_dislikenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(max_length=50)),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BBSPost')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BBSUser')),
            ],
        ),
    ]
