# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_userreportpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbscourse',
            name='C_Comnum',
            field=models.IntegerField(default=0),
        ),
    ]
