# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_remove_bbsuser_u_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbsuser',
            name='U_NewUser',
            field=models.IntegerField(default=0),
        ),
    ]
