# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20170322_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBSDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Code', models.IntegerField(default=0)),
                ('D_Name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
