# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_bbsdept'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbscourse',
            name='C_CorNum',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.BBSDept'),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Exam',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Feature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Guide',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Intro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_PostG',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Pre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Snd',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Teacher',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_Textbook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bbscourse',
            name='C_UnderG',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bbscourse',
            name='C_SeqNum',
            field=models.IntegerField(default=0),
        ),
    ]
