# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20170710_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbscourse',
            name='C_Rank',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
