# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20170710_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbscourse',
            name='C_CorNum',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
