# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-10 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20170710_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbscourse',
            name='C_Dept',
            field=models.IntegerField(null=True),
        ),
    ]
